@echo off
setlocal

set REPO_DIR=C:\Users\quint\olympic-paints-vd
set VD_DIR=C:\Users\quint\OneDrive\1.Projects\1.Olympic Paints\2.Areas\1. Sales\New Sales Targets and Pricing\vd-rebate-system
set LOG_DIR=%USERPROFILE%\.claude\logs\vd-rebate
if not exist "%LOG_DIR%" mkdir "%LOG_DIR%"

echo [%date% %time%] === VD Publish start === >> "%LOG_DIR%\publish.log" 2>&1

:: 1. Rebuild dashboard/index.html from parquet
cd /d "%REPO_DIR%"
python build_vd_dashboard.py >> "%LOG_DIR%\publish.log" 2>&1
if errorlevel 1 (
    echo [%date% %time%] ERROR: build_vd_dashboard.py failed >> "%LOG_DIR%\publish.log" 2>&1
    exit /b 1
)

:: 2. Copy latest rep preview HTMLs (generated by email_reports.py at 08:15)
for %%R in (AC AP BM BV NP) do (
    copy /Y "%VD_DIR%\preview\daily_rep_%%R.html" "%REPO_DIR%\preview\daily_rep_%%R.html" >> "%LOG_DIR%\publish.log" 2>&1
)

:: 3. Stage, commit and push (only if there are changes)
cd /d "%REPO_DIR%"
git add dashboard\index.html preview\daily_rep_AC.html preview\daily_rep_AP.html preview\daily_rep_BM.html preview\daily_rep_BV.html preview\daily_rep_NP.html >> "%LOG_DIR%\publish.log" 2>&1

git diff --cached --quiet
if errorlevel 1 (
    git commit -m "chore(vd): auto-refresh dashboard data for current month" >> "%LOG_DIR%\publish.log" 2>&1
    powershell -NoProfile -Command "$t=gh auth token --user FlomaticAuto 2>$null; $b=[Convert]::ToBase64String([Text.Encoding]::ASCII.GetBytes('x-access-token:'+$t)); git -c \"http.extraheader=AUTHORIZATION: basic $b\" push origin master" >> "%LOG_DIR%\publish.log" 2>&1
    echo [%date% %time%] Pushed to GitHub. >> "%LOG_DIR%\publish.log" 2>&1
) else (
    echo [%date% %time%] No changes — skip push. >> "%LOG_DIR%\publish.log" 2>&1
)

echo [%date% %time%] === VD Publish done === >> "%LOG_DIR%\publish.log" 2>&1
